site_name: Fuse
site_description: Tensor‑equation DSL as a library (NumPy + Torch/JAX)
site_url: https://example.com/fuse
repo_url: https://github.com/example/fuse
repo_name: fuse-ai/fuse

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
    - toc.follow
  icon:
    repo: material/github

nav:
  - Overview: index.md
  - Get Started: get-started.md
  - Tutorials:
      - tutorials/index.md
  - How-to Guides:
      - how-to/index.md
  - Concepts:
      - concepts/index.md
      - DSL Reference: dsl_reference.md
      - Backend Matrix: backend_matrix.md
  - API Reference: reference/index.md
  - CLI: cli.md
  - Community: community.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_object_full_path: false
            docstring_style: google
            docstring_section_style: list
            filters:
              - '!^_'  # hide private members
            members_order: source
          setup_commands:
            - import sys
            - sys.path.insert(0, 'src')
  - gen-files
  - literate-nav
  - section-index
  - mike
  - link-check

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra:
  analytics:
    # Set via an override file for production deployments
    provider: google
    property: G-XXXXXXXXXX
  version:
    provider: mike

watch:
  - src
  - docs

hooks:
  - docs/_scripts/gen_ref_pages.py
