site_name: Fuse
site_description: Tensor‑equation DSL as a library (NumPy + Torch/JAX)
site_url: https://www.neuralint.io/fuse/docs/
repo_url: https://github.com/mehrdadxzaker/fuse/site/
repo_name: fuse
use_directory_urls: true

theme:
  name: material
  language: en
  logo: assets/logo.svg
  favicon: assets/logo.svg
  font:
    text: "Inter"
    code: "JetBrains Mono"
  palette:
    - scheme: default
      primary: indigo
      accent: deep orange
    - scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - toc.follow
  icon:
    repo: material/github

nav:
  - Overview:
      - Welcome: index.md
      - Get Started: get-started.md
  - Tutorials:
      - tutorials/index.md
  - How-to Guides:
      - how-to/index.md
  - Concepts:
      - Overview: concepts/index.md
      - DSL Reference: dsl_reference.md
      - Backend Matrix: backend_matrix.md
  - API Reference:
      - reference/index.md
  - CLI: cli.md
  - Community: community.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          load_external_modules: true
          options:
            show_root_heading: true
            show_object_full_path: false
            docstring_style: google
            docstring_section_style: list
            filters:
              - '!^_'  # hide private members
            members_order: source
  - gen-files:
      scripts:
        - docs/_scripts/gen_ref_pages.py
  - literate-nav
  - section-index
  - mike

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji

extra:
  analytics:
    # Set via an override file for production deployments
    provider: google
    property: G-XXXXXXXXXX
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

watch:
  - src
  - docs
