from __future__ import annotations

from pathlib import Path
import mkdocs_gen_files


SRC_DIR = Path("src")
PACKAGE = "fuse"

nav = mkdocs_gen_files.Nav()

modules = []
for path in sorted(SRC_DIR.rglob("*.py")):
    rel = path.relative_to(SRC_DIR).with_suffix("")
    parts = list(rel.parts)
    # Only document our package
    if parts[0] != PACKAGE:
        continue
    mod_name = ".".join(parts)
    modules.append((parts, mod_name))

    doc_path = Path("reference", *parts, "index.md")
    nav_path = parts[1:]  # drop top-level package from nav root

    nav[tuple(nav_path)] = doc_path.as_posix()

    with mkdocs_gen_files.open(doc_path, "w") as fd:
        fd.write(f"# {mod_name}\n\n")
        fd.write("::: " + mod_name + "\n")
        fd.write("    options:\n")
        fd.write("      show_root_heading: true\n")
        fd.write("      members_order: source\n")
        fd.write("      show_signature: true\n")
        fd.write("      filters:\n")
        fd.write("        - '!^_'\n")

# Write summary nav and landing page
with mkdocs_gen_files.open("reference/SUMMARY.md", "w") as fd:
    fd.write(nav.build_literate_nav())

with mkdocs_gen_files.open("reference/index.md", "w") as fd:
    fd.write("# API Reference\n\n")
    fd.write(
        "Autogenerated from Python docstrings via mkdocstrings. "
        "Browse the modules using the navigation.\n"
    )

