name: Docs

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-docs:
    name: Build MkDocs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Build docs
        run: mkdocs build --strict

  linkcheck:
    name: Link Check (external)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lychee Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: |
            --verbose --no-progress README.md docs/**/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

